services:
  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data
    command: ["sh", "-c", "exec redis-server --dir /data --dbfilename redis_miner --requirepass \"$$REDIS_PASSWORD\""]
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - REDIS_PASSWORD=tinntenRedis123
    networks:
      - tinnten-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - tinnten-net

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - tinnten-net

volumes:
  redis_data:
  esdata:

networks:
  tinnten-net:
    driver: bridge
